//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jogador.java
//  @ Date : 15/06/2010
//  @ Author : 
//
//




public class Jogador extends Integrante {
	public Object aposta;
	public Object total;
	public void dividir() {
	
	}
	
	public void comprarSeguro() {
	
	}
	
	public void finalizar() {
	
	}
}
