//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Banca.java
//  @ Date : 15/06/2010
//  @ Author : 
//
//




public class Banca extends Integrante {
	public void darCartas() {
	
	}
	
	public void perguntarAoJogador() {
	
	}
	
	public void completarJogo() {
	
	}
}
