//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BlackJack.java
//  @ Date : 15/06/2010
//  @ Author : 
//
//




public class BlackJack {
}
