//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Integrante.java
//  @ Date : 15/06/2010
//  @ Author : 
//
//




public class Integrante extends BlackJack {
	public Carta mao;
	public void pedir() {
	
	}
	
	public void ficar() {
	
	}
}
