//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Monte.java
//  @ Date : 15/06/2010
//  @ Author : 
//
//




public class Monte {
	public Baralho baralhos;
	public void embaralhar() {
	
	}
	
	public void descartarCarta() {
	
	}
}
